### ISSUE TITLE
Error: "M_LIMIT_EXCEEDED"

### ISSUE THREAD

**Issue by Vrozaksen** [matrixgpt/matrix-chatgpt-bot#116]
Logs:

`Feb 21 22:35:03 matrix matrix-bot-chatgpt[1935147]: Tue, 21 Feb 2023 22:35:03 GMT [ERROR] [MatrixHttpClient] (REQ-5) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Feb 21 22:35:03 matrix matrix-bot-chatgpt[1935147]: Tue, 21 Feb 2023 22:35:03 GMT [ERROR] [MatrixHttpClient] (REQ-6) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Feb 21 22:35:03 matrix matrix-bot-chatgpt[1935147]: Tue, 21 Feb 2023 22:35:03 GMT [INFO] [MatrixClientLite] End-to-end encryption enabled
Feb 21 22:35:03 matrix matrix-bot-chatgpt[1935147]: Tue, 21 Feb 2023 22:35:03 GMT [INFO] [index] Bot started!
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: Tue, 21 Feb 2023 22:35:04 GMT [ERROR] [MatrixHttpClient] (REQ-10) {
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   errcode: 'M_LIMIT_EXCEEDED',
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   error: 'Too Many Requests',
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   retry_after_ms: 9457
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: }
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: /usr/src/app/node_modules/matrix-bot-sdk/src/http.ts:110
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:         throw new MatrixError(errBody, response.statusCode);
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:               ^
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: MatrixError: M_LIMIT_EXCEEDED: Too Many Requests
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     at doHttpRequest (/usr/src/app/node_modules/matrix-bot-sdk/src/http.ts:110:15)
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     at MatrixClient.descriptor.value (/usr/src/app/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:32)
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     at MatrixClient.descriptor.value (/usr/src/app/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:32) {
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   body: {
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     errcode: 'M_LIMIT_EXCEEDED',
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     error: 'Too Many Requests',
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:     retry_after_ms: 9457
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   },
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   statusCode: 429,
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   errcode: 'M_LIMIT_EXCEEDED',
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   error: 'Too Many Requests',
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]:   retryAfterMs: 9457
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: }
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: Node.js v19.6.0
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: error Command failed with exit code 1.
Feb 21 22:35:04 matrix matrix-bot-chatgpt[1935147]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Vrozaksen** [comment]
Solution:
https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#set-ratelimit
https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/
