### ISSUE TITLE
Error: maxPromptTokens + max_tokens (3097 + 1024 = 4121) must be less than or equal to maxContextTokens (3072)

### ISSUE THREAD

**Issue by breakingflower** [matrixgpt/matrix-chatgpt-bot#279]
What did you do: 
`docker compose pull` 

What version are you running:
- [latest](https://github.com/orgs/matrixgpt/packages/container/matrix-chatgpt-bot/181731191?tag=latest) --> v3.1.5

What happened:
On run, it produces the following error:  
```
yarn run v1.22.19
$ node --enable-source-maps dist/index.js
file:///usr/src/app/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:72
            throw new Error(`maxPromptTokens + max_tokens (${this.maxPromptTokens} + ${this.maxResponseTokens} = ${this.maxPromptTokens + this.maxResponseTokens}) must be less than or equal to maxContextTokens (${this.maxContextTokens})`);
                  ^

Error: maxPromptTokens + max_tokens (3097 + 1024 = 4121) must be less than or equal to maxContextTokens (3072)
    at ChatGPTClient.setOptions (file:///usr/src/app/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:72:19)
    at new ChatGPTClient (file:///usr/src/app/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:23:14)
    at main (file:///usr/src/app/dist/index.js:62:21)
    at file:///usr/src/app/dist/index.js:94:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
error Command failed with exit code 1.
```

What did you try: 
- Adjust `CHATGPT_MAX_CONTEXT_TOKENS=3072`, to try to reduce the value to be < 4096 (e.g. 4096 - 1024 = 3072). This is not taken into account

What did you expect:
- No error

I'm not sure what the root cause is for this issue

**Comment by rmi1974** [comment]
I adjusted `CHATGPT_MAX_PROMPT_TOKENS` in my container env which works fine.

```
# (maxPromptTokens + max_tokens) must be less than or equal to maxContextTokens
- CHATGPT_MAX_PROMPT_TOKENS=3072
```

**Comment by breakingflower** [comment]
Correct, only now replaced by [this issue](https://github.com/matrixgpt/matrix-chatgpt-bot/issues/283)

**Comment by gurbina93** [comment]
After adding this to the 'env' file and recreating the container worked great.

`CHATGPT_MAX_PROMPT_TOKENS=3072`

For those using etke.cc you can find it under /matrix/chatgpt/config/env
