### ISSUE TITLE
Timeout when trying to authenticate on https://chat.openai.com

### ISSUE THREAD

**Issue by N3oTraX** [matrixgpt/matrix-chatgpt-bot#70]
Hello,

I'm not able to connect to https://chat.open.ai through the bot and my docker system.
I tried the v1.4.1 latest release and the actual master branch to deploy it.
The bot can connect to my matrix server but in the container log I obtain this return :

```
yarn run v1.22.19
mtx-chatgpt  | $ node dist/index.js
mtx-chatgpt  | /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64
mtx-chatgpt  |                 this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
mtx-chatgpt  |                                ^
mtx-chatgpt  |
mtx-chatgpt  | TimeoutError: Waiting for selector `input[type="password"]` failed: Waiting failed: 30000ms exceeded
mtx-chatgpt  |     at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
mtx-chatgpt  |     at listOnTimeout (node:internal/timers:564:17)
mtx-chatgpt  |     at process.processTimers (node:internal/timers:507:7)
mtx-chatgpt  |
mtx-chatgpt  | Node.js v19.4.0
mtx-chatgpt  | error Command failed with exit code 1.
mtx-chatgpt  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
mtx-chatgpt exited with code 1
mtx-chatgpt exited with code 1
mtx-chatgpt  | xvfb-run: error: Xvfb failed to start
mtx-chatgpt exited with code 1
mtx-chatgpt exited with code 1
mtx-chatgpt  | xvfb-run: error: Xvfb failed to start
mtx-chatgpt exited with code 1
mtx-chatgpt exited with code 1
mtx-chatgpt  | xvfb-run: error: Xvfb failed to start
mtx-chatgpt exited with code 1
mtx-chatgpt  | xvfb-run: error: Xvfb failed to start
mtx-chatgpt exited with code 1
mtx-chatgpt exited with code 1
mtx-chatgpt  | xvfb-run: error: Xvfb failed to start
mtx-chatgpt exited with code 1
mtx-chatgpt exited with code 1
mtx-chatgpt  | xvfb-run: error: Xvfb failed to start
```

After the 5th attempt I get a context destroyed like that (which seems to be normal) :

```
 yarn run v1.22.19
mtx-chatgpt  | $ node dist/index.js
mtx-chatgpt  | /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:174
mtx-chatgpt  |     return new Errors_js_1.TimeoutError(errorMessage);
mtx-chatgpt  |            ^
mtx-chatgpt  |
mtx-chatgpt  | TimeoutError: Navigation timeout of 30000 ms exceeded
mtx-chatgpt  |     at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:174:12)
mtx-chatgpt  |     at async Frame.waitForNavigation (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:274:23)
mtx-chatgpt  |     at async CDPPage.waitForNavigation (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:449:16)
mtx-chatgpt  |     at async Promise.all (index 0)
mtx-chatgpt  |     at async getOpenAIAuth (file:///usr/src/app/node_modules/chatgpt/build/index.js:865:9)
mtx-chatgpt  |     at async ChatGPTAPIBrowser.initSession (file:///usr/src/app/node_modules/chatgpt/build/index.js:1394:24)
mtx-chatgpt  |     at async main (file:///usr/src/app/dist/index.js:38:5)
mtx-chatgpt  |
mtx-chatgpt  | Node.js v19.4.0
mtx-chatgpt  | error Command failed with exit code 1.
mtx-chatgpt  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Between the time I launch the container and the timeout error the bot is trying to answer me if I talk to him but never answer really untill the timeout occurs. Then the bot disconnect after my container tries 5 connexion attempt to openai URL.

I tried to deploy the bot with docker-compose or through docker run directly. In network host mode or through my usual proxy but I always get the same timeout error.
In all cases above I try master branch or 1.4.1 release behind, and not behind proxy or in network host mode to avoid passing through docker-proxy network.

This is my .env file : 

```
# == ChatGPT Matrix bot
# ChatGPT Settings (required)
OPENAI_EMAIL=hidden+bot@gmail.com
OPENAI_PASSWORD=hidden
OPENAI_LOGIN_TYPE=google
OPENAI_PRO=false
CHATGPT_CONTEXT=both
MATRIX_HOMESERVER_URL=https://hidden_matrix_server_url
# With the @ and :DOMAIN, ie @SOMETHING:DOMAIN - Not used if `MATRIX_ACCESS_TOKEN` is set.
#MATRIX_BOT_USERNAME=@hidden_bot_name:hidden_matrix_server_url
# Not used if `MATRIX_ACCESS_TOKEN` is set.
#MATRIX_BOT_PASSWORD=hidden_bot_paswword
# Set `MATRIX_BOT_PASSWORD` the bot will print an `MATRIX_ACCESS_TOKEN` to the terminal
MATRIX_ACCESS_TOKEN=hidden_token

# Matrix Configurable Settings Defaults (optional)
MATRIX_DEFAULT_PREFIX=
MATRIX_DEFAULT_PREFIX_REPLY=false

# Matrix Access Control (optional)
# Can be set to user:homeserver or a wildcard like :anotherhomeserver.example
MATRIX_BLACKLIST=
# `MATRIX_WHITELIST` is overriden by `MATRIX_BLACKLIST` if they contain same entry
MATRIX_WHITELIST=

# Matrix Feature Flags (optional)
MATRIX_AUTOJOIN=true
MATRIX_ENCRYPTION=false

MATRIX_THREADS=true
MATRIX_PREFIX_DM=false
MATRIX_RICH_TEXT=true
```

I deploy it with docker-compose file : 
```
  mtx-chatgpt:
    <<: *common-keys-core # Extensions which set my restart policy and proxy configured network
    #build: ./custom/chatgpt
    image: ghcr.io/matrixgpt/matrix-chatgpt-bot:latest
    env_file: ./custom/chatgpt/.env
    container_name: mtx-chatgpt
    #network_mode: host
    volumes:
      - $DOCKERDIR/appdata/mtx/chatgpt/data:/storage
```

Or directly with a docker run like that :

```
docker run -it -v /docker/infra2/appdata/mtx/chatgpt/data/:/storage --env-file=/docker/infra2/custom/chatgpt/.env --name mtx-chatgpt ghcr.io/matrixgpt/matrix-chatgpt-bot:latest 
```

Trying a curl inside and outside the container give me the same result :
```
root@e1e3423276ba:/usr/src/app# curl https://chat.openai.com
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">


</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            chat.openai.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=791240479d4c2a62')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            chat.openai.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/?__cf_chl_f_tk=O2A9qQ6lLPwa4NfLu08AsZfEg4nReZ82kU.EJuSx9Gs-1674998278-0-gaNycGzNBz0" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="EN5fsHmwCwtZPTHxmQwYlxHcpM9ZFbzIJ5.W3grabmA-1674998278-0-AaQGFvDTYmPgGTZIJJpHC-ebB567HtANqUltAjNSU5Xxzjqa_OP9Gwxly6Qcdk3qX_vLYM1I-BoP852N3ofRrr9l-j6FZzKOcH4NhkKcgNn9Ir67K8mwV8d5NrZv3AiVE24Jsa5zjX2K0cQCqopnDb7DWbHABjrPnoY3htWaxb8ednp2VKtZx3qMvXKDIhM7Ina7yBi4Kz3qmVgkbh2Yo2xRgncmxajS8WwUkW7UIHqkYThVsnsiFlHJPIZtE5qB5PBaIvw4RT6ca3D_NLLOY6HoCvqGrlvb4zcFKblfwAcbLgylOb6qWh2NrGPzRR3npY4VyMVr_bZo00LEoP2PpdWM6JhTApnPmsTXGY0CZeLNkm9eSZkuv8qEQFpGi59t5yKr45K_MSw-0jyIRuR1t99SpoL0YMPgUB7Tx4N8djwvgS85ZriScE4oA3GgkfoSTGDb5akwJuq0emyIfw9DS3ETd8fbPRRMXdCkHjLM845_">
            <input type="hidden" name="r" value="k_Vsiv.LcSRhjvLUh8Ioh0QSU0V_X56NJpt91LfT1Pc-1674998278-0-Aa6z9JDqki0eeVOBIJYoyqLe5iXDBOkX0RajvF7cBsf0D2/Yh2KbxJVEp0QGRmuv+PCbttvL3XU1EhMR1DwZZGUjBXwzJgnZ1XUJP0C0CiJZK/gjcbYbvlu2no82WyWsl4yZNjmbgSzy+z+aQBo63YJiJmkYjdPdwYT8qdEB66CfkdmnZk1pKkzw1pzo2y56PaCtUQOsXgMZ6sU0vyoHL6pEF27+ADLB0l5Xw2lEKMM+m1ZIgv9XZbk+pHOpKotKCc8Od1NhfboR+2lkaa0ypvMJgo5OBryVz28dV1NnKf89GCcypaSEXgSm57JR8laDft4X3DamSP1D3XeAhNY5qwkwiZuk/KF76kZAJnXcnR3fylLmgF5bdDcX64TyViVcteAIOC1cN+zCM/+3hoQFDCxboinXAAhog8nXAt0ufyxiKJJm1WLSAtt9a4aSBKXXTN9cQ9/tVL5wN3WsZQhlhsb6bLPR4p70aDHccJ3TVtS4TTrprFkEb17d9hCTB6q1RePHc5mRxChmjX/CCyQaQQD9yLF7RxNUVGtEPZ+u6hKGY9tDRaLmGguO8YEwFAWtFPNhlHBR1lqcH0SflwfNle/mS+blrgxj+80ixH/VYD3e+1A7rJQnmLeCZHhSOJjElfJyuC2Z2l4hNpn2GPqxHXkvrp8ocX0RzghaUlQUNZlUaTZikcilpI0rlKsD5SmOu6c3VunGzT63V7OCeu+dshZPGV1vGMAJyMz9PajVqBU/nLmmBQNHcXQ4YCG/iIowm07+a5gYnh0EcbisgmVQ6W68WGdmUN98BP/EVOy4Gc5iCRncDSzkUAnoJMGOeMlzuaWgJBikzzNjJ+/HFQo7SXEhaSU3mfqeXZ/3U95y3kTPuXhxbt/wp7KxlvqoADjykQj7P4QYAg+4rpf8Xaze1oPRCDULsMs2zWnbcL9qE5fEEWA2M9HMT/0Cd88JBJ1Kyc5OQX8/zzhcHaDxwiR+/dmzlT4jJvjKD8eN9hGP1Y1buIt2K72iYCf24oZYVn8yGlSdk27xLVQVKW2JUc7zd6G7RxkkFMcE+io4vh2xfcxdOqEQpoWW6IlztHYIJoKAT1GS2rMs/BQgKGQrzh5HDeySSi+dXrnHwOZvwrLw3FerDqqVjbwUvDe0LkfrdnhRPmTooY8I4uDR0zgHSC8G123/d0k9i6c4MbvoOtJJbIuXqVVzekBc+d3CUbGrhloe2WlXegwZ/qyjZ0O7RTww4n0Kw5TY7C6CnqMAGFIwpQvoallwph4+BN0whstQOtabGlx4UCNTjqe9juGWkzd8d4U/13XitazDk/J7p1EC4NzViMT2ACz6Do8fhfL7oedz2iFxA4u2iKWOe8Ay5qWT1rebBqyAP0LmOPemsmTMuTWoddsVxchM91E+tcO5AxDZAR+nVZi2ZSr4DdTIRo6b8lrh1c/oqfd1OMwWEP1RrJ3/LmnA1z5txCS4MXwbT4vAm4WaFIVyC10IPxU3xVvLJ+WomFpCow+8mwWFfAqz2PWlfML2Uog62Ojs7OnuVYGBGH7gPPbXm4nOOCLl01YEMAoTeWOJFFX4/RSCamuC+QiG2eFMkNYJM4gL/1VDbnoizC1t1f7czVuZxhvsFiZI4iyB/Ya8g+c5R1JuB2o0k3D6KXJXsP0tudJ5RLfKmgpI/Av+1BeNNJj7BmmEpaL3Qt8VUPxlLaMXlxmx/QLPOm4fBiL2z1gXHbfifD2rhk4DxGAHtPAyRuZi7VWNHEjFBwWsNk/av1Hznb7dp+0EzlbfL4b7NoldBP4MDKeNznDOmw==">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'chat.openai.com',
            cType: 'managed',
            cNounce: '50371',
            cRay: '791240479d4c2a62',
            cHash: '461614ae53ff89e',
            cUPMDTk: "\/?__cf_chl_tk=O2A9qQ6lLPwa4NfLu08AsZfEg4nReZ82kU.EJuSx9Gs-1674998278-0-gaNycGzNBz0",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9jaGF0Lm9wZW5haS5jb20vY2hhdC9mcm9udGVuZC8=',
                ra: 'Y3VybC83Ljc0LjA=',
                rm: 'R0VU',
                d: '4onh1UzsrHq1K2gnTfg3Gp0aKgAHhQeP+AHpIPLze77jgIz/Y/kg3ZkjwyWQdxzv5noIrVn+ke3PWCNl/xNdEcM2yuynhV0tcKhUtCSCBD3e+PLYApfNNi/VM+28rA7EJumDGfylVzL8dHA8W9BKz/HRPG6wUBYlN/ytIK5S6PhdXuHDrDjPBDxlKoQxSmACrBOCbgx/czT0CCtLBUsbRwTucqP32tgvFa6PgYLVE/KeEuJfg0Rk/xiWNqpGTgNLd3575CtiiBo6xkMfO0Iv2TrN/ru3rxi30kB1pysTLqNbiSffW8UybKjYMA65dMb0U0pL0yLIk4yirnQVsyWtQ9xXixirlYG51rb2FPgyl0MSuk9Fk1xUGlarQQ+vGCigz7TZUkZ0g5d3uRpSraJbDGVfdct/5d2JNzSOKncANNxVmhO+ugjQjE4qngLK9a1EuoKAejxyYbbiOqlF+U2gnnRxkQf9yhAmrbI/70+7o4DUQTK7O8Nw3vaCQNnqLCnub+o0VNL61xXUQuXPvBgm2kFdxbfjSVSb+LRf4rqJPuT97bQAwDpGtMecI3/+Veo2hK+9N12VY2uExqXtjxNoJSWJW/EIG3duAesJ8CqLZFJ7XG2ljTHiNhu8vDbPo4JTXjwOy+7BW4QKygVvUL46ZGGxF1AQanlGb8GOtYEBw3Q=',
                t: 'MTY3NDk5ODI3OC4zNDEwMDA=',
                m: 'KgY0+JCfkcifjRYdZuMJ1H6twEKiFB8rWc6fLBUmgFo=',
                i1: 'xOvHMmzbvgFIxbW40diuWA==',
                i2: 'JRd5XcTBmPf0oWSFk9O0Yg==',
                zh: 'iuyN59AGNgeBFFEOPj72EN+xtBfXXvoCyd1dJnIVFAc=',
                uh: 'zu+cQgicc5rF6Q8HHTJhdGCD3QVkjetpkn+QXGMpZBU=',
                hh: 'foaWmAUHGGlVCZaNUJIHhxzxFNzSPNnVe6rJjiQw728=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=791240479d4c2a62');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=791240479d4c2a62';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/?__cf_chl_rt_tk=O2A9qQ6lLPwa4NfLu08AsZfEg4nReZ82kU.EJuSx9Gs-1674998278-0-gaNycGzNBz0" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>791240479d4c2a62</code></div>
            </div>
            <div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
```

I hope all these informations can help.

Best regards,

**Comment by bertybuttface** [comment]
Possibly related: https://github.com/transitive-bullshit/chatgpt-api/issues/277

**Comment by bertybuttface** [comment]
Closing because his package will be switching to use the official API so this will no longer be relevant.
