### ISSUE TITLE
Invalid URI?

### ISSUE THREAD

**Issue by 42Willow** [matrixgpt/matrix-chatgpt-bot#84]
docker run -it -v storage:/storage --env-file=./.env --name matrix-chatgpt-bot ghcr.io/matrixgpt/matrix-chatgpt-bot:latest
yarn run v1.22.19
$ node --enable-source-maps dist/index.js
Sun, 05 Feb 2023 07:30:49 GMT [ERROR] [MatrixHttpClient] (REQ-1) Error: Invalid URI "%22https://matrix.org%22/_matrix/client/v3/login"
    at Request.init (/usr/src/app/node_modules/request/request.js:273:31)
    at new Request (/usr/src/app/node_modules/request/request.js:127:8)
    at request (/usr/src/app/node_modules/request/index.js:53:10)
    at respIsBuffer (/usr/src/app/node_modules/matrix-bot-sdk/src/http.ts:78:23)
    at new Promise (<anonymous>)
    at doHttpRequest (/usr/src/app/node_modules/matrix-bot-sdk/src/http.ts:77:41)
    at MatrixClient.doRequest (/usr/src/app/node_modules/matrix-bot-sdk/src/MatrixClient.ts:2006:29)
    at MatrixClient.descriptor.value (/usr/src/app/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:53)
    at MatrixAuth.passwordLogin (/usr/src/app/node_modules/matrix-bot-sdk/src/MatrixAuth.ts:118:60)
    at main (file:///usr/src/app/dist/index.js:44:76)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Invalid URI "%22https://matrix.org%22/_matrix/client/v3/login"
    at Request.init (/usr/src/app/node_modules/request/request.js:273:31)
    at new Request (/usr/src/app/node_modules/request/request.js:127:8)
    at request (/usr/src/app/node_modules/request/index.js:53:10)
    at respIsBuffer (/usr/src/app/node_modules/matrix-bot-sdk/src/http.ts:78:23)
    at new Promise (<anonymous>)
    at doHttpRequest (/usr/src/app/node_modules/matrix-bot-sdk/src/http.ts:77:41)
    at MatrixClient.doRequest (/usr/src/app/node_modules/matrix-bot-sdk/src/MatrixClient.ts:2006:29)
    at MatrixClient.descriptor.value (/usr/src/app/node_modules/matrix-bot-sdk/src/metrics/decorators.ts:28:53)
    at MatrixAuth.passwordLogin (/usr/src/app/node_modules/matrix-bot-sdk/src/MatrixAuth.ts:118:60)
    at main (file:///usr/src/app/dist/index.js:44:76)

Node.js v19.6.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 42Willow** [comment]
Never mind I forgot to enter the access token 🤦

**Comment by dillfrescott** [comment]
Odd because I set the access token and im still getting this error

**Comment by dillfrescott** [comment]
It works without docker though running it manually

**Comment by tcpipuk** [comment]
Have you put quotes around the server URL in the config file? That very much looks like what's going on based on this URL in the error: `%22https://matrix.org%22/_matrix/client/v3/login`

**Comment by dillfrescott** [comment]
I believe I tried it both with and without the quotes
